let express = require('express')
let router = express.Router()
let {body} = require('express-validator')
let UserController = require('../controllers/user-controller')
let CardController = require('../controllers/card-controller')
let TransactionController = require('../controllers/transaction-controller')
let SupportController = require('../controllers/support-controller')
let authMiddleware = require('../middlewares/auth-middleware')

router.post('/registration', body('mail').isEmail(), body('password').isLength({min: 5, max: 32}), UserController.registration)
router.post('/login', UserController.login)
router.get('/activate', UserController.activate)
router.get('/refresh', UserController.refresh)
router.get('/user/main', authMiddleware, UserController.main)
router.post('/user/fill', authMiddleware, UserController.fill)
router.post('/card/create', CardController.create)
router.get('/card/get', CardController.get)
router.delete('/card/delete', CardController.delete)
router.post('/transaction/crypt', TransactionController.crypt)
router.post('/payment/create', TransactionController.paymentCreate)
router.post('/transaction/create', TransactionController.create)
router.get('/oplata/get', TransactionController.oplata)
router.post('/transaction/accept', TransactionController.accept)
router.post('/support/ask', authMiddleware, SupportController.ask)
router.get('/support/messages', SupportController.messages)
router.post('/logout', UserController.logout)

module.exports = router